version: '3'
services:
  rust_backend:
    build: .
    volumes:
      - './:/usr/src/problemarena'
    depends_on:
      - postgres-cluster-ip-service
      - ai_backend
    ports:
      - '8000'
    networks:
      - app-network
  ai_backend:
    build:
      context: ./ai
      dockerfile: Dockerfile
    volumes:
      - './ai:/app'
    ports:
      - '8080'
    networks:
      - app-network
  postgres-cluster-ip-service:
    image: 'postgres:15.2-alpine'
    environment:
      - POSTGRES_DB=infoarena
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=013551
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge