ALTER TABLE UserCredentials
ADD COLUMN CONFIRMED bool NOT NULL DEFAULT FALSE;

ALTER TABLE UserCredentials
    ADD COLUMN CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE UserCredentials
    ADD COLUMN UUID varchar NOT NULL DEFAULT '' UNIQUE;