pub mod problem_controller;
pub mod user_controller;
pub mod submission_controller;
pub mod contest_controller;
pub mod participates_controller;
pub mod authentication_controller;
pub mod admin_controller;
pub mod chat_controller;
pub(crate) mod chat;
mod hate_speech;